version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD 
    
    steps:
      - run: apt-get update && apt-get install -y git ssh unzip

      - run: 
          name: Install z3 
          command: |
            wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.8/z3-4.8.8-x64-ubuntu-16.04.zip
            unzip z3-4.8.8-x64-ubuntu-16.04.zip
            rm -f z3-4.8.8-x64-ubuntu-16.04.zip
            cp z3-4.8.8-x64-ubuntu-16.04/bin/libz3.a /usr/local/lib
            cp z3-4.8.8-x64-ubuntu-16.04/bin/z3 /usr/local/bin
            cp z3-4.8.8-x64-ubuntu-16.04/include/* /usr/local/include
            rm -rf z3-4.8.8-x64-ubuntu-16.04
            z3 --version
      - checkout
      - add_ssh_keys

      - run:
          name: Test Examples 
          command: stack setup && stack build
